# Configuration file for Kara. The wgpu powered digital assistant.
[general-settings]
# Kara has two modes, a graphical session, and a terminal session.
# You can set your preference by using "gui" or "cli" respectively.
# The value passed as a CLI arg takes priority.
default-mode = "gui"

# Set the log level. Possible values are:
# "trace", "debug", "info", "warn", "error" in increasing level of
# importance. Kara will output the current log level as well as
# all log levels to the right (of the list above).
# If set to debug: debug, info, warn, and error events are emmitted.
# If set to warn: only warn and error events are emmitted.
# The value passed as a CLI arg takes priority.
log-level = "warn"

# The default specification for units Kara should assume
units = "metric" 

[natural-language-understanding]

[natural-language-understanding.speech-to-text]
# Number of seconds for Kara to listen for silence before processing
# a command.
pause-length = 2.0

# Source for Speech to Text
# Available values are "kara", "gcp", "aws", "azure", "watson"
# "kara" is a fallback source if there is an issue with a configured service
source = "kara"

[natural-language-understanding.speech-to-text.kara]
# Your .tflite model file. (https://stt.readthedocs.io/en/latest/)
model-path = ""

# Whether to use an external language scorer. If specified, transcription
# results may be improved.
scorer-path = ""

#[natural-language-understanding.speech-to-text.watson]
# call external program (gpg or pass?) so as to not store plain text config in file?
