[package]
name = "kara-nlu"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
snips-nlu-lib = { git = "https://github.com/kawaki-san/snips-nlu-rs", branch = "kawaki-patch" }
serde_json = "1.0.82"
