[package]
name = "kara-audio"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tracing = "0.1.34"
rustfft = "6.0.1"
cpal = "0.13.5"
apodize = "1.0.0"
